### PR TITLE
Watts

### PR DESCRIPTION
**Pull request by rwatts3**
Updates the Sidebar to be a bootstrap navbar. Allowing it to collapse when viewing the admin panel from a mobile app. Also adds a nice background to separate the sidebar from the main view.

### CODE REVIEW

**Comment by rwatts3** [comment]
Here is an example of what the admin panel looks like. 

Collapsed View
image

Open View
image

**Comment by rwatts3** [comment]
Also at the top where it says 'Orion Admin' there is a dictionary assignment for `{ dict 'appName'}` If defined This will display in the in stead of `Orion Admin` if it is not defined the admin name will display `Orion Admin` . There is also a link that takes you to the home page of the site when clicked. This fixes my question about rendering a `Home` link as a sidebar item. So that the user doesn't have to remove `\admin\` from the url.

**Comment by nicolaslopezj** [comment]
Great update. Please make only the changes available for small screens. Also I'm having some issues with text colors
captura de pantalla 2015-03-31 a las 12 38 40 1

**Comment by rwatts3** [comment]
Could you elaborate a little on the comment? You mean only make it collapsable with the Orion Admin included for small screen or would you like the Orion Admin link to also be at the mobile and desktop view.

**Comment by nicolaslopezj** [comment]
I mean that we should only add the background to the sidebar on small screens and for large screens leave the transparent background as we have it now.
And the thing is that when the sidebar is with the background we should change the color of the font and remove the text shadows

**Comment by rwatts3** [comment]
Got it . I will work on the updates and commit. I'll let you know once these are complete.

**Comment by nicolaslopezj** [comment]
Exellent

**Comment by rwatts3** [comment]
Ok latest two commits from April 2 addresses the sidebar background color issue, and allows it to be transparent as it was before. The dropdown for the sidebar only kicks in when the device is at mobile view. 

Ryan .

**Comment by nicolaslopezj** [comment]
Very nice!

**Comment by nicolaslopezj** [comment]
I changed the ```appName``` to```siteName```

**Comment by rwatts3** [comment]
Awesome happy to see this get added to the core.

**Pull request merged**
