### PR TITLE
Support for custom entity

### PR DESCRIPTION
**Pull request by timfam**
Done, cleaned up and working

### CODE REVIEW

**Comment by rwatts3** [comment]
@timfam 
This looks really good, could you tell me what this update does. I have not had a chance to look at the code but i'm curious to know what new options are available. 
Great work btw.

**Comment by timfam** [comment]
I am writing the currently writing the tutorial it will be up in 10-15 mins or less

**Comment by rwatts3** [comment]
Awesome.

**Comment by timfam** [comment]
tutorial here https://github.com/orionjs/tutorials/blob/master/Custom%20Entity%20Templates.md

**Comment by rwatts3** [comment]
Hi @timfam 
The tutorial looks really good an informative, but I would like to add some advice. When @nicolaslopezj and I first talked about tutorials we agreed that within the tutorials there should be a detailed explanation of the component or item you are adding, but there should also be a working example, where the user can create a project, and follow your tutorial step by step and result with a working example of your implementation. We will probably want to go back and add to the tutorial another section that literally holds the hand of the user and gives them a finished product.

**Comment by rwatts3** [comment]
Hmm disregard everything I just wrote, when I first looked at the tutorial you must have still been writing it or something because it looks completely different now from what I first saw. It looks like you have already done everything I said in the above comment. 

Great work man !

**Comment by rwatts3** [comment]
@timfam 
Question , so let's say I was creating a sidebar item called Analytics which will contain graphs and other pieces of information. Could I use your update to show graphs on the page ?

**Comment by timfam** [comment]
This is really to allow orion use all the power of autoform in content management. It has very little to do with how you display the content. Let say you have a form where user must select city and other fields are dependent on the city they chose, afQuickfield is a must in such a situation

**Comment by rwatts3** [comment]
Ah i see , well i'm looking forward to using this update .

**Comment by rwatts3** [comment]
Have you heard anything back on whether Aldeed will add support for Tooltip or Helptips on the form. I feel that this is needed, and the last I check he was looking for help from the community to build an add on package

**Comment by timfam** [comment]
I think he just released version 5, plenty of overhaul going on in that package to make it more compartible with meteor 1+ When things settle down a bit it will be easier to contribute

**Comment by rwatts3** [comment]
Ok

**Comment by nicolaslopezj** [comment]
There are conflicts, please update the pr

**Comment by timfam** [comment]
@nicolaslopezj  Updated it to match your last commit, please accept PR

**Comment by nicolaslopezj** [comment]
I dont know why but it says there are still conflicts, I will try to solve them myself

**Comment by timfam** [comment]
I don't see where the conflicts is coming from. I just cloned your last commit and added in my fixes. Beats me

**Pull request merged**
